### ISSUE TITLE
Allow configuration without requiring project fork

### ISSUE THREAD

**Issue by niansa** [ADBeta/CH32V003_lib_uart#6]
Currently if you want to change configuration you have to fork the project and change the config in the header. Maintaining forks for little things like that sucks.
If the configuration wasn't hardcoded inside the header you could simply git submodule this project.

**Comment by ADBeta** [comment]
The intention was never to support for branches changing configuration. the point is to let people just download the .c and .h, use them as they please, and configure them as they see fit. I'm not trying to make a library for everyone to jump in on. I am making a library for a project I'm working on, which just happens to be generic and useful enough that others can change it for what they need.

I don't aim for perfection, just useful-ness :)
Be my guest to fork, and change the code in whatever way you want, and make the library useful in the way you want. That's why I wrote it

**Comment by niansa** [comment]
I see.
